sudo: required
services:
  - docker

before_install:
  - docker build -t itamar/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run itamar/react/test npm test -- --coverage

after_sucess:
  - docker build -t itamar/multi-client ./client
  - docker build -t itamar/multi-nginx ./nginx
  - docker build -t itamar/multi-server ./server
  - docker build -t itamar/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push itamar/multi-client
  - docker pushitamar/multi-nginx 
  - docker pushitamar/multi-server
  - docker pushitamar/multi-worker